[package]
name = "graph-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = {version = "0.28.0", features = ["nom_parser", "pom_parser"]}
# pdf = "0.7.2"
